export const genres = ['All', 'Platformer', 'Fun', 'Horror', 'Shooter', 'Puzzle', 'Racing',"Word", "Survival"];
/* 'Roguelite', 'Exploration', 'Dungeon Crawler', 'Narrative', 'Life Sim', 'Horror', 'Shooter', 'Puzzle', 'Relaxing', 'Fishing', 'Space' */
export const platforms = ['All', 'PC', 'Mobile', 'Web'];
export const statuses = ['All', 'Played', 'Completed', 'Demo'];


export const games = [
  {
    id: 22,
    releaseDate: "2026-07-11",
    title: "VERDANT",
    thumbnail: 'thumbnails/22.png',
    tags: ['3D', 'Shooter', 'Survival'],
    platform: ['Web'],
    videoUrl: 'https://youtu.be/zW7Boh3gVRM',
  },
   {
    id: 21,
    releaseDate: "2026-07-05",
    title: "Word Hullabaloo",
    thumbnail: 'thumbnails/21.png',
    tags: ['2D', 'Word'],
    platform: ['PC'],
    videoUrl: 'https://youtu.be/4qlSYSjQMz4',
  },
  {
    id: 20,
    releaseDate: "2026-07-01",
    title: "Dark Queen Of Samobor",
    thumbnail: 'thumbnails/18.png',
    tags: ['3D', 'Unity', 'Platformer'],
    platform: ['PC'],
    videoUrl: 'https://youtu.be/_unhLdkqfoI',
  },
  {
    id: 19,
    releaseDate: "2026-06-27",
    title: "ROLLA",
    thumbnail: 'thumbnails/17.png',
    tags: ['3D', 'Unity', 'Fun'],
    platform: ['PC'],
    videoUrl: 'https://youtu.be/3SkaN0N38f4',
  },
  {
    id: 18,
    releaseDate: "2026-06-20",
    title: "BLEEDING",
    thumbnail: 'thumbnails/16.png',
    tags: ['3D', 'Unity', 'Shooter'],
    platform: ['PC'],
    videoUrl: 'https://youtu.be/ycKgPdpzXAw',
  },
  {
    id: 17,
    releaseDate: "2026-06-20",
    title: "Lil Baby Poop's NIGHTMARES",
    thumbnail: 'thumbnails/15.png',
    tags: ['2D', 'Godot', 'Fun', 'Platformer'],
    platform: ['PC'],
    videoUrl: 'https://youtu.be/gWjGHfkkfGA',
  },
  {
    id: 16,
    releaseDate: "2026-06-17",
    title: "Moss Moss",
    thumbnail: 'thumbnails/14.png',
    tags: ['2D', 'Puzzle', 'Platformer'],
    platform: ['PC', 'Web'],
    videoUrl: 'https://youtu.be/DUi81gsdweM',
  },
  {
    id: 15,
    releaseDate: "2026-06-02",
    title: "Costly Curiosity",
    thumbnail: 'thumbnails/13.png',
    tags: ['2D', 'Fun', 'Horror'],
    platform: ['Web'],
    videoUrl: 'https://youtu.be/HWW3UFn7kbY',
  },
  {
    id: 14,
    releaseDate: "2026-05-26",
    title: "Carrot Kingdom",
    thumbnail: 'thumbnails/12.png',
    tags: ['2D', 'Puzzle', 'Platformer'],
    platform: ['Web'],
    videoUrl: 'https://youtu.be/bx4NotPfcJs',
  },
  {
    id: 13,
    releaseDate: "2026-05-16",
    title: "Beyond the Roots",
    thumbnail: 'thumbnails/11.png',
    tags: ['2D', 'Godot', 'Platformer'],
    platform: ['PC', 'Web'],
    videoUrl: 'https://youtu.be/nB-Db9xonxw',
  },
  {
    id: 12,
    releaseDate: "2026-05-12",
    title: "HER TREES",
    thumbnail: 'thumbnails/10.png',
    tags: ['2D', 'Unity', 'Puzzle'],
    platform: ['PC', 'Web'],
    videoUrl: 'https://youtu.be/pDhiYPJ__ec',
  },
  {
    id: 11,
    releaseDate: "2026-05-06",
    title: "FLAKE ❄ The Legend of Snowblind",
    thumbnail: 'thumbnails/9.png',
    tags: ['2D', 'Unity', 'Story', 'Click'],
    platform: ['PC'],
    videoUrl: 'https://youtu.be/xDqI6OX3ivk',
  },
  {
    id: 10,
    releaseDate: "2026-04-25",
    title: "Tales of Isenberg",
    thumbnail: 'thumbnails/8.png',
    tags: ['2D', 'Godot', 'Platformer'],
    platform: ['PC'],
    videoUrl: 'https://youtu.be/u2vNDziHiM4',
  },
  {
    id: 9,
    releaseDate: "2026-04-22",
    title: "RD Racing",
    thumbnail: 'thumbnails/7.png',
    tags: ['3D', 'Unity', 'Racing'],
    platform: ['PC'],
    videoUrl: 'https://youtu.be/VU5tfkUdKk8',
  },
  {
    id: 8,
    releaseDate: "2026-04-18",
    title: "Print Gallery Of An Artist",
    thumbnail: 'thumbnails/6.png',
    tags: ['2D', 'Platformer'],
    platform: ['PC', 'Web'],
    videoUrl: 'https://youtu.be/JuWpo0cuRPs',
  },
  {
    id: 7,
    releaseDate: "2026-04-12",
    title: "Simons Shift",
    thumbnail: 'thumbnails/4.png',
    tags: ['3D', 'Unity', 'Horror'],
    platform: ['PC'],
    videoUrl: 'https://youtu.be/hI4FWDdNDp8',
  },
  {
    id: 6,
    releaseDate: "2026-04-10",
    title: "Feed The Ai",
    thumbnail: 'thumbnails/5.png',
    tags: ['2D', 'Unity', 'Click'],
    platform: ['PC', 'Web'],
    videoUrl: 'https://youtu.be/oKpr4ZdjsZs',
  },
  {
    id: 5,
    releaseDate: "2026-04-07",
    title: "Dog Finding Home",
    thumbnail: 'thumbnails/3.png',
    tags: ['2D', 'Unity', 'Platformer'],
    platform: ['PC', 'Web'],
    videoUrl: 'https://youtu.be/jU5ZZBMjXXs',
  },
  {
    id: 4,
    releaseDate: "2026-04-06",
    title: "Push The Square",
    thumbnail: 'thumbnails/2.png',
    tags: ['2D', 'Unity', 'Fun'],
    platform: ['PC', 'Web'],
    videoUrl: 'https://youtu.be/82LukboHfXg',
  },
  {
    id: 3,
    releaseDate: "2026-04-04",
    title: "Gogo's Quest",
    thumbnail: 'thumbnails/1.png',
    tags: ['2D', 'Unity', 'Platformer'],
    platform: ['PC', 'Web'],
    videoUrl: 'https://youtu.be/aZR9LFDu_Ow',
  },
  {
    id: 2,
    releaseDate: "2026-04-03",
    title: 'Pizza Horizon',
    thumbnail: 'thumbnails/s2.png',
    tags: ['3D', 'Unity', 'Racing'],
    platform: ['PC', 'Web'],
    videoUrl: 'https://youtu.be/Tlrx9mcvB90',
  },
  {
    id: 1,
    releaseDate: "2026-04-03",
    title: "The Quiet Quit",
    thumbnail: 'thumbnails/s1.png',
    tags: ['3D', 'Unity', 'Puzzle'],
    platform: ['PC', 'Web'],
    videoUrl: 'https://youtu.be/zGtrhxfF6aY',
  },
];



export const developers = [
  {
    slug: 'echo-labs',
    name: 'Echo Labs',
    bio: 'Small two-person studio based in Helsinki. They make dark atmospheric games with heavy emphasis on sound design and environmental storytelling.',
    featuredGame: 'Hollow Vale',
    intro: 'Echo Labs was founded in 2021 by two lifelong friends who wanted to make the kinds of games they couldn\'t find anywhere else.',
    gameInfo: 'Hollow Vale is their debut release — a metroidvania set in a world on the brink of forgetting itself.',
    thoughts: 'I played this game over three nights and couldn\'t stop thinking about it after. The world-building is extraordinary for such a small team.',
    gamePageUrl: 'https://echolabs.itch.io',
    twitter: 'https://twitter.com',
  },]