export const games = [
  {
    id: 1,
    title: 'Hollow Vale',
    description: 'A melancholic metroidvania set in a crumbling underground kingdom. The atmosphere is unmatched.',
    thumbnail: null,
    tags: ['Metroidvania', 'Puzzle'],
    platform: 'PC',
    status: 'Completed',
    videoUrl: 'https://youtube.com',
  },
  {
    id: 2,
    title: 'Neon Rift',
    description: 'Fast-paced roguelite shooter with procedurally generated levels and gorgeous pixel art.',
    thumbnail: null,
    tags: ['Roguelite', 'Shooter'],
    platform: 'PC',
    status: 'Played',
    videoUrl: 'https://youtube.com',
  },
  {
    id: 3,
    title: 'Verdant Echoes',
    description: 'A meditative exploration game about restoring a dying forest. Incredibly peaceful.',
    thumbnail: null,
    tags: ['Exploration', 'Relaxing'],
    platform: 'PC',
    status: 'Completed',
    videoUrl: 'https://youtube.com',
  },
  {
    id: 4,
    title: 'Cryptwell',
    description: 'Tense dungeon crawler with permanent death and genuinely terrifying monster design.',
    thumbnail: null,
    tags: ['Dungeon Crawler', 'Horror'],
    platform: 'PC',
    status: 'Demo',
    videoUrl: 'https://youtube.com',
  },
  {
    id: 5,
    title: 'Starbound Drifter',
    description: 'Space exploration with a focus on narrative choices and emergent storytelling.',
    thumbnail: null,
    tags: ['Narrative', 'Space'],
    platform: 'PC',
    status: 'Played',
    videoUrl: 'https://youtube.com',
  },
  {
    id: 6,
    title: 'Saltmarsh',
    description: 'A fishing and life sim set in a slowly flooding coastal village. Bittersweet.',
    thumbnail: null,
    tags: ['Life Sim', 'Fishing'],
    platform: 'PC',
    status: 'Completed',
    videoUrl: 'https://youtube.com',
  },
];

export const developers = [
  {
    slug: 'echo-labs',
    name: 'Echo Labs',
    bio: 'Small two-person studio based in Helsinki. They make dark atmospheric games with heavy emphasis on sound design and environmental storytelling.',
    featuredGame: 'Hollow Vale',
    intro: 'Echo Labs was founded in 2021 by two lifelong friends who wanted to make the kinds of games they couldn\'t find anywhere else.',
    gameInfo: 'Hollow Vale is their debut release — a metroidvania set in a world on the brink of forgetting itself.',
    thoughts: 'I played this game over three nights and couldn\'t stop thinking about it after. The world-building is extraordinary for such a small team.',
    gamePageUrl: 'https://echolabs.itch.io',
    twitter: 'https://twitter.com',
  },
  {
    slug: 'sable-works',
    name: 'Sable Works',
    bio: 'Solo developer crafting roguelites with tight mechanics and pixel art. Previously worked in mobile before going indie.',
    featuredGame: 'Neon Rift',
    intro: 'One person, one studio, one mission: make games that feel amazing to play.',
    gameInfo: 'Neon Rift is a fast-paced roguelite shooter that rewards pattern recognition and quick reflexes.',
    thoughts: 'The gunplay in Neon Rift is some of the best I\'ve felt in an indie game. Every run feels different and interesting.',
    gamePageUrl: 'https://sableworks.itch.io',
    twitter: 'https://twitter.com',
  },
  {
    slug: 'fernwood-studio',
    name: 'Fernwood Studio',
    bio: 'Three developers with a passion for cozy, thoughtful games that don\'t ask too much of the player but give back deeply.',
    featuredGame: 'Verdant Echoes',
    intro: 'Fernwood was born out of a shared belief that games can be peaceful and still be meaningful.',
    gameInfo: 'Verdant Echoes puts you in charge of restoring a dying magical forest through careful observation and gentle interaction.',
    thoughts: 'I played this on a rainy afternoon and it was exactly what I needed. Quiet, beautiful, and surprisingly emotional.',
    gamePageUrl: 'https://fernwoodstudio.itch.io',
    twitter: 'https://twitter.com',
  },
];

export const genres = ['All', 'Metroidvania', 'Roguelite', 'Exploration', 'Dungeon Crawler', 'Narrative', 'Life Sim', 'Horror', 'Shooter', 'Puzzle', 'Relaxing', 'Fishing', 'Space'];
export const platforms = ['All', 'PC', 'Mac', 'Linux', 'Switch', 'Mobile'];
export const statuses = ['All', 'Played', 'Completed', 'Demo'];
